food/urls.py
from django.contrib import admin
from django.urls import include,path
from menu import views
from users import views as user_views
from django.contrib.auth import views as authencication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('menu.urls')),
    path('', views.start, name="start"),
    path('register/', user_views.register, name='register'),
    path('login/', authencication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authencication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/',user_views.profile, name='profile'),


]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from . import views
from django.urls import path

app_name = 'menu'
urlpatterns = [
    path('',views.IndexClassView.as_view(), name='index'),
    path ('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('items/', views.items,name='items'),
    path('dodaj', views.CreateItem.as_view(), name='create_item'),
    path('edit/<int:id>/', views.edit_item, name='edit_item'),
    path('delete/<int:id>', views.delete_item, name='delete_item'),
    path('location/', views.location, name='location'),
    path('about/', views.about, name='about'),
]

menu/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse



# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.FloatField()
    item_img = models.CharField(max_length=500, default="https://assets.materialup.com/uploads/b03b23aa-aa69-4657-aa5e-fa5fef2c76e8/preview.png")

    def get_absolute_url(self):
        return reverse("menu:detail", kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

menu/forms.py
from django import forms
from .models import Item



class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_img']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username' , 'email', 'password1', 'password2']

menu/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ItemForm
from .models import Item
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required

# Create your views here.



class IndexClassView(ListView):
    model = Item;
    template_name = 'menu/index.html'
    context_object_name = 'item_list'

def items(request):
    return HttpResponse('Widok pozycji menu')

def start(request):
    return render(request, 'menu/start.html')



class FoodDetail(DetailView):
    model = Item;
    template_name = 'menu/detail.html'


def create_item(request):

        form = ItemForm(request.POST or None)

        if form.is_valid():
            form.save()
            return redirect('menu:index')

        return render(request, 'menu/item-form.html', {'form':form})

class CreateItem(LoginRequiredMixin ,CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_img']
    template_name = 'menu/item-form.html'


    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)

@login_required
def edit_item(request, id):
    item = Item.objects.get(id=id)
    form =  ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('menu:index')
    return render(request, 'menu/item-form.html', {'form':form, 'item':item})

def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('menu:index')

    return render(request, 'menu/item-delete.html', {'item':item})

def location(request):
    return render(request, 'menu/location.html')

def about(request):
    return render(request, 'menu/about.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
    if request.method =='POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Witaj {username}, twoje konto zostalo utowrzone')
            return redirect ('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form':form})

@login_required
def profile(request):
    return render(request,'users/profile.html')

templates/menu/about.html
{% extends 'menu/base.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    {% block body %}

        to do

    {% endblock %}



</body>
</html>

templates/menu/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'menu/style.css' %}">



    <title>Document</title>

</head>
<body>

        
        <nav class="navbar navbar-dark" style="background-color: #9376E0">

            <a href="{% url 'start' %}" class="navbar-brand">
                <img id="logo" src="{% static 'menu/logo.png' %}">
                Restaurant

            </a>


            <div class="navbar">
                <form class="form-check-inline">
                    <a class="nav-item active nav-link text-white" href="{% url 'menu:create_item' %}"> Add item </a>
                    <a class="nav-item active nav-link text-white" href="{% url 'register' %}"> Register </a>
                    <a class="nav-item active nav-link text-white" href="http://127.0.0.1:8000/admin"> Admin </a>
                    {% if user.is_authenticated %}
                        <a class="nav-item active nav-link text-white" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-item active nav-link" style="color: #343A40" href="{% url 'logout' %}"> Logout </a>

                    {% else %}
                        <a class="nav-item active nav-link text-white" id="login" href="{% url 'login' %}">Login</a>
                    {% endif %}
                </form>
            </div>
        </nav>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                {{ message }}
                 </div>
            {% endfor %}
        {% endif %}
    {% block body %}
    {% endblock %}

</body>
</html>

templates/menu/detail.html
{% extends 'menu/base.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    {% block body %}

        <div class="container">
            <div class="row">
                <div class="col-md-4">
                   <img class="card" src="{{ item.item_img }}" height="150px"/>
                </div>

                <div class="col-md-4">
                    <h1>{{ object.item_name }}</h1>
                    <h2>{{ object.item_desc }}</h2>
                    <h3>{{ object.item_price }} PLN</h3>
                    <a class="btn btn-danger" id="del" href="{% url 'menu:delete_item' item.id %}">Delete
                    </a>
                    <a class="btn btn-info" href="{% url 'menu:edit_item' item.id %}">Edit</a>
                </div>
            </div>
        </div>






    {% endblock %}
</body>
</html>

templates/menu/index.html
{% extends 'menu/base.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>

<body>
    {% block body %}

        {% for item in item_list %}

            <div class="row">
                <div class="col-md-3 offset-md-2">
                    <img class="card" height="150px" src="{{ item.item_img }}"/>
                </div>

                <div class="col-md-4">
                    <h3>{{ item.item_name }}</h3>
                    <h5>{{ item.item_desc }}</h5>
                    <h6>{{ item.item_price }} PLN</h6>
                    <h6>Added by: {{ item.user_name }}</h6>
                </div>

                <div class="col-md-2">
                    <a href="{% url 'menu:detail' item.id  %}" class="btn btn-outline-info">Details</a>
                </div>

            </div>

        {% endfor %}

    {% endblock %}








   
</body>
</html>

templates/menu/item-delete.html
{% extends 'menu/base.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>

<body>
    {% block body %}

       <form method="POST">
    {% csrf_token %}
           <div class="col-md-4 offset-md-5">
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
</div>
           <div class="row">
                <div class="col-md-3 offset-md-2">
                    <img class="card" height="150px" src="{{ item.item_img }}"/>
                </div>

                <div class="col-md-4">

                    <h5>{{ item.item_desc }}</h5>
                    <h6>{{ item.item_price }} PLN</h6>
                    <h6>Added by: {{ item.user_name }}</h6>
                </div>
           </div>
    <button type="submit" class="btn btn-danger col-md-1 offset-md-5" id="del">Confirm</button>

</form>

    {% endblock %}









</body>
</html>

templates/menu/item-form.html
{% extends 'menu/base.html' %}

{% block body %}
 <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4 ">
                <div class="card">
                    <div class="card-header text-white" style="background-color: #343A40">
                        <div class="card-title">
                            <h2>Add Item</h2>
                        </div>
                    </div>
                    <div class="card-body"  style="background-color: #9376E0">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form" style="color: black">
                            {{ form }}

                                <button class="text-white" style="background-color: #343A40" type="submit"> Add </button>

                            </div>
                </form>

                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/menu/location.html
{% extends 'menu/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}

Insert google maps here
    {% endblock %}



</body>
</html>

templates/menu/start.html
{% extends 'menu/base.html' %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta
			name="viewport"
			content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<title>Document</title>
	</head>
	<body>
		{% block body %}

		<div class="container">
			<div class="row">
				<div class="col-md-4 offset-md-4 align-middle">
					 <a class="btn btn-outline-primary" href="{% url 'menu:index'%}">View Menu
                    </a>
                     <a class="btn btn-outline-primary" href="{% url 'menu:location'%}">Location
                    </a>
                     <a class="btn btn-outline-primary" href="{% url 'menu:about'%}">About us
                    </a>
				</div>

				<div class="col-md-4"></div>
			</div>
		</div>

		{% endblock %}
	</body>
</html>

templates/users/login.html
{% extends 'menu/base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header  text-white" style="background-color: #343A40">
                        <div class="card-title">
                            <h2>Login</h2>
                        </div>
                    </div>
                    <div class="card-body" style="background-color: #9376E0">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group" >
                                    {{ field.name }}
                                    {{ field }}
                                </div>

                            {% endfor %}
                            <button class="text-white" style="background-color: #343A40" type="submit">Login</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

templates/users/logout.html
{% extends 'menu/base.html' %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% block body %}

      <h1>You have been logged out</h1>

      <a class="btn btn-outline-success" href="{% url 'start'%}">Go back to the main page
                    </a>



{% endblock %}
</body>
</html>

templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}">

templates/users/register.html
{% extends 'menu/base.html' %}

{% block body %}
 <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4" >
                <div class="card">
                    <div class="card-header text-white" style="background-color: #343A40">
                        <div class="card-title">
                            <h2>Register</h2>
                        </div>
                    </div>
                    <div class="card-body" style="background-color: #9376E0">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group" style="color: black">
                                    {{ field.name }}
                                    <br>
                                    {{ field }}

                                </div>


                            {% endfor %}



                            <button class="text-white" type="submit" style="background-color: #343A40"> Register </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}